create table detector
(
    id    bigserial,
    place varchar(50),
    constraint detector_pk
        primary key (id)
);

create unique index detector_id_uindex
    on detector (id);

create table capture
(
    plate_number varchar(255),
    photo_url    varchar(500),
    place        varchar(255),
    time_stamp   timestamp,
    id           bigint generated by default as identity (maxvalue 2147483647),
    constraint capture_pkey
        primary key (id)
);

create table detector_previous_detectors_distance
(
    detector_id                     integer not null,
    previous_detectors_distance     integer,
    previous_detectors_distance_key integer not null,
    constraint detector_previous_detectors_distance_pkey
        primary key (detector_id, previous_detectors_distance_key),
    constraint fkh1i8qcn22pgbgkqpqmr25sp21
        foreign key (previous_detectors_distance_key) references detector,
    constraint fk9c9vhvgh3gam50mp8dldmch7a
        foreign key (detector_id) references detector
);

