# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches:
      - main
    paths:
      - authentication/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./authentication/gradlew bootJar
  copy:
    runs-on: ubuntu-latest
    steps:
    - name: copy jar file to gradle
      run: ssh -i $${{ secrets.SSH}} 
    - name: Build with Gradle
      run: ./authentication/gradlew bootJar
    - name: Copy single file to remote
      uses: garygrossgarten/github-action-scp@release
      with:
        local: test/oof.txt
        remote: scp/single/oof.txt
        host: ${{ secrets.HOSTAuth }}
        username: ${{ secrets.SSH_USER}}
        password: ${{ secrets.PASSWORD}}


      
